### ISSUE TITLE
Mozilla Firefox API support link 503

### ISSUE THREAD

**Issue by JayAndCatchFire** [bfred-it/Awesome-WebExtensions#34]
The link for Mozilla Firefox API support (http://arewewebextensionsyet.com/) is currently broken.  I don't know of a suitable replacement site.

**Comment by bfred-it** [comment]
You’re right, site was decommissioned. https://github.com/andymckay/arewewebextensionsyet.com


I think the other compatibility tables already on the list are good replacements. PR welcome to remove it

**Comment by JayAndCatchFire** [comment]
incoming PR

**Comment by bfred-it** [comment]
Thanks! Appreciated
